# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pmaxit.github.io/aibook/"

git_url = "https://github.com/pmaxit/aibook/tree/main/"

def custom_doc_links(name): return None
